import { create } from 'zustand'
import { createJSONStorage, persist } from 'zustand/middleware'

import { createId } from '@/lib/id'
import { STORAGE_KEYS } from '@/lib/storageKeys'
import type { Invite, InviteChannel, RsvpStatus } from '@/types'

import { useContactStore } from './useContactStore'
import { useEventStore } from './useEventStore'
import { useNotificationStore } from './useNotificationStore'

export interface CreateInviteInput {
  /**
   * Generated by the caller (via lib/id's createInviteToken) *before* the
   * invite is created, so the composer can build and preview the bespoke
   * RSVP link/message ahead of persisting anything.
   */
  token: string
  eventId: string
  contactId: string
  templateId: string
  subject: string
  message: string
}

export interface SubmitResponseExtra {
  guestCount?: number
  responseNote?: string
}

interface InviteState {
  invites: Invite[]
  createInvites: (inputs: CreateInviteInput[]) => Invite[]
  recordSend: (inviteId: string, channel: InviteChannel) => Invite | undefined
  markViewed: (token: string) => Invite | undefined
  submitResponse: (token: string, response: RsvpStatus, extra?: SubmitResponseExtra) => Invite | undefined
  updateInviteMessage: (inviteId: string, patch: { subject?: string; message?: string }) => void
  deleteInvite: (id: string) => void
  deleteInvitesForEvent: (eventId: string) => void
  deleteInvitesForContact: (contactId: string) => void
}

function responseLabel(response: RsvpStatus): string {
  if (response === 'yes') return 'is coming 🎉'
  if (response === 'no') return "can't make it"
  return 'might come'
}

export const useInviteStore = create<InviteState>()(
  persist(
    (set, get) => ({
      invites: [],

      createInvites: (inputs) => {
        const now = new Date().toISOString()
        const created = inputs.map<Invite>((input) => ({
          id: createId(),
          token: input.token,
          eventId: input.eventId,
          contactId: input.contactId,
          templateId: input.templateId,
          subject: input.subject,
          message: input.message,
          status: 'draft',
          sends: [],
          viewCount: 0,
          response: 'pending',
          createdAt: now,
          updatedAt: now,
        }))
        set({ invites: [...created, ...get().invites] })
        return created
      },

      recordSend: (inviteId, channel) => {
        const existing = get().invites.find((inv) => inv.id === inviteId)
        if (!existing) return undefined
        const updated: Invite = {
          ...existing,
          status: existing.status === 'draft' ? 'sent' : existing.status,
          sends: [...existing.sends, { channel, sentAt: new Date().toISOString() }],
          updatedAt: new Date().toISOString(),
        }
        set({ invites: get().invites.map((inv) => (inv.id === inviteId ? updated : inv)) })
        return updated
      },

      markViewed: (token) => {
        const existing = get().invites.find((inv) => inv.token === token)
        if (!existing) return undefined
        const now = new Date().toISOString()
        const updated: Invite = {
          ...existing,
          status: existing.status === 'responded' ? existing.status : 'viewed',
          firstViewedAt: existing.firstViewedAt ?? now,
          lastViewedAt: now,
          viewCount: existing.viewCount + 1,
          updatedAt: now,
        }
        set({ invites: get().invites.map((inv) => (inv.token === token ? updated : inv)) })
        return updated
      },

      submitResponse: (token, response, extra) => {
        const existing = get().invites.find((inv) => inv.token === token)
        if (!existing) return undefined

        const isChange = existing.response !== 'pending'
        const now = new Date().toISOString()
        const updated: Invite = {
          ...existing,
          status: 'responded',
          response,
          respondedAt: now,
          guestCount: extra?.guestCount,
          responseNote: extra?.responseNote,
          updatedAt: now,
        }
        set({ invites: get().invites.map((inv) => (inv.token === token ? updated : inv)) })

        const contact = useContactStore.getState().contacts.find((c) => c.id === updated.contactId)
        const event = useEventStore.getState().events.find((e) => e.id === updated.eventId)
        const name = contact?.name ?? 'A guest'
        const label = responseLabel(response)

        useNotificationStore.getState().addNotification({
          type: 'rsvp_response',
          eventId: updated.eventId,
          inviteId: updated.id,
          contactId: updated.contactId,
          response,
          title: isChange ? `${name} updated their response` : `${name} responded`,
          body: event ? `${name} ${label} to "${event.title}".` : `${name} ${label}.`,
        })

        return updated
      },

      updateInviteMessage: (inviteId, patch) => {
        set({
          invites: get().invites.map((inv) =>
            inv.id === inviteId ? { ...inv, ...patch, updatedAt: new Date().toISOString() } : inv,
          ),
        })
      },

      deleteInvite: (id) => set({ invites: get().invites.filter((inv) => inv.id !== id) }),

      deleteInvitesForEvent: (eventId) =>
        set({ invites: get().invites.filter((inv) => inv.eventId !== eventId) }),

      deleteInvitesForContact: (contactId) =>
        set({ invites: get().invites.filter((inv) => inv.contactId !== contactId) }),
    }),
    {
      name: STORAGE_KEYS.invites,
      storage: createJSONStorage(() => localStorage),
    },
  ),
)
